#!/bin/bash

cat /dev/null | java -Xmx768M -XX:MaxPermSize=250m \
    -Dsbt.log.noformat=true \
    -Dbuild.number="$BUILD_NUMBER" \
    -Dbuild.vcs.number="$BUILD_VCS_NUMBER" \
    -Dhttp.proxyHost=devscreen.gudev.gnl \
    -Dhttp.proxyPort=3128 \
    -jar sbt-launch-0.11.2.jar "$@"

